config/routes.rb
Rails.application.routes.draw do
  resources :employees do
    resources :bills
  end

  resources :departments

  root 'employees#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :employee
  enum bill_type: {food: 'Food',travel: 'Travel', others: 'Others'}
  validates :amount, presence: true
  validates :bill_type, presence: true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :employees

    validates :name, presence: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  has_many :bills, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
    before_action :set_employee, only: [:index, :new, :create]
  
    def index
      @bills = @employee.bills
    end
  
    def new
      @bill = @employee.bills.build
    end
  
    def create
      @bill = @employee.bills.build(bill_params)
      if @bill.save
        redirect_to employee_bills_path(@employee), notice: 'Bill was successfully created.'
      else
        render :new
      end
    end
  
    private
  
    def set_employee
      @employee = Employee.find(params[:employee_id])
    end
  
    def bill_params
      params.require(:bill).permit(:amount, :bill_type)
    end
  end
  

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
    def index
      @departments = Department.all
    end
  
    def show
      @department = Department.find(params[:id])
    end
  
    def new
      @department = Department.new
    end
  
    def create
      @department = Department.new(department_params)
      if @department.save
        redirect_to @department, notice: 'Department was successfully created.'
      else
        render :new
      end
    end
  
    def edit
      @department = Department.find(params[:id])
    end
  
    def update
      @department = Department.find(params[:id])
      if @department.update(department_params)
        redirect_to @department, notice: 'Department was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @department = Department.find(params[:id])
      @department.destroy
      redirect_to departments_url, notice: 'Department was successfully destroyed.'
    end
  
    private
  
    def department_params
      params.require(:department).permit(:name)
    end
  end
  

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    def index
      @employees = Employee.includes(:department).all
    end
  
    def show
      @employee = Employee.find(params[:id])
      @bills = @employee.bills
    end
  
    def new
      @employee = Employee.new
      @departments = Department.all
    end
  
    def create
      @employee = Employee.new(employee_params)
      if @employee.save
        redirect_to @employee, notice: 'Employee was successfully created.'
      else
        @departments = Department.all
        render :new
      end
    end
  
    def edit
      @employee = Employee.find(params[:id])
      @departments = Department.all
    end
  
    def update
      @employee = Employee.find(params[:id])
      if @employee.update(employee_params)
        redirect_to @employee, notice: 'Employee was successfully updated.'
      else
        @departments = Department.all
        render :edit
      end
    end
  
    def destroy
      @employee = Employee.find(params[:id])
      @employee.destroy
      redirect_to employees_url, notice: 'Employee was successfully destroyed.'
    end
  
    private
  
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email, :designation, :department_id)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bills/index.html.erb
<h1 class="display-4 text-center my-4">Bills for <%= @employee.first_name %> <%= @employee.last_name %></h1>

<div class="container">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Amount</th>
        <th>Type</th>
        <th>Date Submitted</th>
      </tr>
    </thead>
    <tbody>
      <% @bills.each do |bill| %>
        <tr>
          <td><%= bill.amount %></td>
          <td><%= bill.bill_type.capitalize %></td>
          <td><%= bill.created_at.strftime("%B %d, %Y") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row">
    <div class="col-md-6 mb-3">
      <%= link_to 'New Bill', new_employee_bill_path(@employee), class: 'btn btn-primary btn-block' %>
    </div>
    <div class="col-md-6 mb-3">
      <%= link_to 'Back to Employees', employees_path, class: 'btn btn-secondary btn-block' %>
    </div>
  </div>
</div>

app/views/bills/new.html.erb
<h1 class="display-4 text-center my-4">New Bill for <%= @employee.first_name %> <%= @employee.last_name %></h1>

<%= form_with(model: [@employee, @bill], local: true, class: 'container') do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :amount %>
        <%= form.number_field :amount, step: 0.01, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :bill_type, 'Type', class: 'd-block' %>
        <%= form.select :bill_type, Bill.bill_types.keys.map { |type| [type.capitalize, type] }, prompt: 'Select Type', class: 'form-control custom-select custom-select-lg' %>
      </div>
    </div>

    <div class="col-12">
      <div class="form-group">
        <div class="row">
          <div class="col-md-6">
            <div class="mb-3">
              <%= link_to 'Back to Bills', employee_bills_path(@employee), class: 'btn btn-secondary btn-block' %>
            </div>
          </div>
          <div class="col-md-6">
            <%= form.submit 'Create Bill', class: 'btn btn-primary btn-block' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1 class="display-4 text-center my-4"><%= action_name.capitalize %> Employee</h1>

<%= form_with(model: @employee, local: true, class: 'container') do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :email, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :designation %>
        <%= form.text_field :designation, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :department_id, 'Department' %>
        <%= form.collection_select :department_id, @departments, :id, :name, prompt: 'Select Department', class: 'form-control custom-select' %>
      </div>
    </div>

    <div class="col-12">
      <div class="form-group">
        <div class="row">
          <div class="col-md-6">
            <%= link_to 'Back', employees_path, class: 'btn btn-secondary btn-block' %>
          </div>
          <div class="col-md-6">
            <%= form.submit 'Create Employee', class: 'btn btn-primary btn-block' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/employees/index.html.erb
<h1>Employees</h1>
<table class="table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Designation</th>
      <th>Department</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_name %></td>
        <td><%= employee.last_name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.designation %></td>
        <td><%= employee.department.name %></td>
        <td>
          <%= link_to 'Show', employee %>
          <%= link_to 'Edit', edit_employee_path(employee) %>
          <%= link_to 'Delete',  employee_path(employee), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<head>
  <style>
    .custom-select {
      background-color: #f8f9fa;
      border-color: #ced4da;
      color: #495057;
    }
    
  </style>

</head>
<h1 class="display-4 text-center my-4"><%= action_name.capitalize %> Employee</h1>

<%= form_with(model: @employee, local: true, class: 'container') do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :email %>
        <%= form.email_field :email, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :designation %>
        <%= form.text_field :designation, class: 'form-control' %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :department_id, 'Department' %>
        <%= form.collection_select :department_id, @departments, :id, :name, prompt: 'Select Department', class: 'form-control custom-select' %>
      </div>
    </div>

    <div class="col-12">
      <div class="form-group">
        <div class="row">
          <div class="col-md-6">
            <%= link_to 'Back', employees_path, class: 'btn btn-secondary btn-block' %>
          </div>
          <div class="col-md-6">
            <%= form.submit 'Create Employee', class: 'btn btn-primary btn-block' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/employees/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-8">
        <h1><%= @employee.first_name %> <%= @employee.last_name %></h1>
  
        <div class="card">
          <div class="card-header">
            Employee Details
          </div>
          <div class="card-body">
            <table class="table">
              <tbody>
                <tr>
                  <th style="width: 30%;">Email</th>
                  <td><%= @employee.email %></td>
                </tr>
                <tr>
                  <th>Designation</th>
                  <td><%= @employee.designation %></td>
                </tr>
                <tr>
                  <th>Department</th>
                  <td><%= @employee.department.name %></td>
                </tr>
                <!-- Add more details as needed -->
              </tbody>
            </table>
          </div>
        </div>
  
        <div class="mt-3">
          <%= link_to 'Edit', edit_employee_path(@employee), class: 'btn btn-primary mr-2' %>
          <%= link_to 'Back', employees_path, class: 'btn btn-secondary' %>
        </div>
  
        <div class="mt-4">
          <h2>Bills</h2>
          <% if @bills.any? %>
            <table class="table table-striped">
              <thead>
                <tr>
                  <th style="width: 30%;">Amount</th>
                  <th>Type</th>
                  <th>Date Submitted</th>
                </tr>
              </thead>
              <tbody>
                <% @bills.each do |bill| %>
                  <tr>
                    <td><%= number_to_currency(bill.amount) %></td>
                    <td><%= bill.bill_type.capitalize %></td>
                    <td><%= bill.created_at.strftime("%B %d, %Y") %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          <% else %>
            <p>No bills submitted yet.</p>
          <% end %>
        </div>
  
        <div class="mt-3">
          <%= link_to 'Create New Bill', new_employee_bill_path(@employee), class: 'btn btn-success' %>
        </div>
      </div>
    </div>
  </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Your Rails App</title>
  <!-- Bootstrap CSS from CDN -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= yield %>
</body>
</html>